"""`ReportModel`: the one shared, validated model both the Markdown and HTML
renderers render from (PROJECT_SPEC.md §M5's "Build one Pydantic report
model and render both formats from it").

**Byte-stability.** No field here is ever populated from wall-clock time,
hostname, current working directory, an absolute filesystem path, or any
runtime-introspected value other than the one deliberately-recorded
`sklearn_version` string. Two `build_report(...)` calls against the same,
unchanged database must produce two `ReportModel`s that serialise
identically -- `tests/test_report_determinism.py` checks this across two
separate process invocations, not just two calls in one process. There is
deliberately no `generated_at`/`rendered_at` timestamp field; if a caller
wants "generated for run X on date Y", that is `Run.started_at`/
`Run.finished_at` data pulled from the database, not render-time
`datetime.now()`.

**Provenance carried, not copied.** Every quote (`EvidenceItem.quote`) is the
literal `Turn.content` of the finding's `evidence_turn_id`, resolved once in
`sul.report.build.build_report` and carried here -- never re-derived, never
excerpted, and never confused with `EvidenceItem.summary` (the Analyst's
paraphrase), which is rendered separately and is never presented inside a
quote or attributed to a persona.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from sul.enums import FindingCategory

SIMULATED_PANEL_CAVEAT = (
    "This report was generated by a panel of LLM-simulated personas, not "
    "real users. Every quote below is model output produced in character, "
    "not something a person said. Treat findings here as hypotheses to "
    "validate with real participants, not as user research on their own."
)


class EvidenceItem(BaseModel):
    """One finding's evidence, as it appears under a cluster in the report."""

    model_config = ConfigDict(extra="forbid")

    finding_id: int
    run_id: int
    persona_name: str
    segment: str
    quote: str
    evidence_turn_ordinal: int
    summary: str


class SegmentBreakdown(BaseModel):
    model_config = ConfigDict(extra="forbid")

    segment: str
    frequency: int
    denominator: int


class ClusterReport(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cluster_id: int
    title: str
    modal_category: FindingCategory
    category_disagreement: bool
    frequency: int
    denominator: int
    mean_severity: float
    segment_breakdown: list[SegmentBreakdown]
    evidence: list[EvidenceItem]


class ExclusionCount(BaseModel):
    model_config = ConfigDict(extra="forbid")

    status: str
    count: int


class ReportModel(BaseModel):
    """Everything both renderers need, and nothing else -- no ORM object, no
    live session, no field populated at render time (see module docstring).
    """

    model_config = ConfigDict(extra="forbid")

    study_id: int
    study_name: str
    total_personas: int
    included_run_count: int
    excluded_runs: list[ExclusionCount]
    total_findings: int
    clusters: list[ClusterReport]
    clustering_distance_threshold: float
    clustering_metric: str
    clustering_linkage: str
    sklearn_version: str
    include_failed: bool


__all__ = [
    "SIMULATED_PANEL_CAVEAT",
    "ClusterReport",
    "EvidenceItem",
    "ExclusionCount",
    "ReportModel",
    "SegmentBreakdown",
]
